app3_PL/Controllers/DepartmentController.cs
using app3.BLL;
using app3.BLL.interfacees;
using app3.BLL.interfaces;
using app3.BLL.Repostry;
using app3.DaL.models;
using app3.PL.Helper;
using app3.PL.ViewModel.Departments;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace app3.PL.Controllers
{
	[Authorize]
	public class DepartmentController : Controller
    {
        //private readonly IDepartmentRepo departmentRepo;
        private readonly IUnitOfWork unitOfWork;
        private readonly IMapper _mapper;

        public DepartmentController(
            //IDepartmentRepo repo,
            IUnitOfWork unitOfWork,
            IMapper mapper
            
            )
        {
            //departmentRepo = repo;
            this.unitOfWork = unitOfWork;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var departments=await unitOfWork.DepartmentRepo.GetAllAsync();
          var department=  _mapper.Map<IEnumerable<DepartmentViewModel>>(departments);
            return View(department);
        }

        [HttpGet]
        public IActionResult Create()
        {
           
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(DepartmentViewModel department)
        {

           var department01=  _mapper.Map<Department>(department);
            if (ModelState.IsValid)
            {
                unitOfWork.DepartmentRepo.AddAsync(department01);
                var count =await unitOfWork.CompleteAsync();


                if (count > 0)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(department);
        }

        public async  Task<IActionResult> Details(int? id ,string viewName="Details")
        {
            if(id is null )
            {
                return BadRequest();//400
            }
           var result=await unitOfWork.DepartmentRepo.GetAsync(id.Value);

            if (result == null)  return NotFound();

          var department=  _mapper.Map<DepartmentViewModel>(result);

            return View(viewName,department);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
        //    if(id is null ) return BadRequest();

        //   var department=departmentRepo.Get(id);
        //    if (department == null) return NotFound();

        //    return View(department);
        return await Details(id,"Edit");
        }
        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute]int? id,DepartmentViewModel department)
        {
           var department01= _mapper.Map<Department>(department);
            try
            {
                if (id != department01.Id) return BadRequest();

                if (ModelState.IsValid)
                {

                    unitOfWork.DepartmentRepo.UpdateAsync(department01);
                    var count =await unitOfWork.CompleteAsync();

                    if (count > 0)
                    {
                        return RedirectToAction("Index");
                    }

                }
             
            }
            catch (Exception EX)
            {
                ModelState.AddModelError(String.Empty, EX.Message);
            }
          

            return View(department);

        }
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return BadRequest();

            var department =await unitOfWork.DepartmentRepo.GetAsync(id.Value);
            if (department == null) return NotFound();
         var department01=   _mapper.Map<DepartmentViewModel>(department);

            return View(department01); 
        }

        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(DepartmentViewModel department)
        {
            if (department == null) return NotFound();
            if (ModelState.IsValid)
            {

                var department01 = _mapper.Map<Department>(department);
                unitOfWork.DepartmentRepo.DeleteAsync(department01);
                var count =await unitOfWork.CompleteAsync();

                if (count > 0)
                {
                    return RedirectToAction("Index");
                }

            }
            
            return RedirectToAction("Delete");
        }
    }



}

app3_PL/Controllers/RoleController.cs
using app3.DaL.models;
using app3.PL.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace app3.PL.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string inputSearch)
        {
            var users = Enumerable.Empty<RoleviewModel>();

            if (string.IsNullOrEmpty(inputSearch))
            {
                users = await _roleManager.Roles.Select(u => new RoleviewModel()
                {
                    Id = u.Id,
                    Name = u.Name
                }).ToListAsync();

            }
            else
            {
                users = await _roleManager.Roles.Where(u => u.Name
                                  .ToLower()
                                  .Contains(inputSearch.ToLower()))
                                  .Select(u => new RoleviewModel()
                                  {
                                      Id = u.Id,
                                      Name = u.Name
                                  }).ToListAsync();
            }



            return View(users);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(RoleviewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole()
                {
                    Name = model.Name,
                };

                await _roleManager.CreateAsync(role);

                return RedirectToAction("Index");


            }

            return View(model);
        }



        public async Task<IActionResult> Details(string? id, string viewName = "Details")
        {

            if (id is null)
            {

                return BadRequest();//400
            }
            var userfromDb = await _roleManager.FindByIdAsync(id);

            if (userfromDb == null) return NotFound();
            var user = new RoleviewModel()
            {
                Id = userfromDb.Id,
                Name = userfromDb.Name,

            };


            return View(viewName, user);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {

            return await Details(id, "Edit");
        }


        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] string? id, RoleviewModel model)
        {

            try
            {
                if (id != model.Id) return BadRequest();

                if (ModelState.IsValid)
                {
                    var userfromDb = await _roleManager.FindByIdAsync(id);

                    if (userfromDb == null) return NotFound();
                    userfromDb.Name = model.Name;
                    await _roleManager.UpdateAsync(userfromDb);


                    return RedirectToAction("Index");


                }

            }
            catch (Exception EX)
            {
                ModelState.AddModelError(String.Empty, EX.Message);
            }



            return View(model);

        }

        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {

            return await Details(id, "Delete");
        }



        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed([FromRoute] string id, RoleviewModel model)
        {
            try
            {
                if (id != model.Id) return BadRequest();

                if (ModelState.IsValid)
                {
                    var userfromDb = await _roleManager.FindByIdAsync(id);

                    if (userfromDb == null) return NotFound();
                    userfromDb.Name = model.Name;
                    await _roleManager.DeleteAsync(userfromDb);


                    return RedirectToAction("Index");


                }

            }
            catch (Exception EX)
            {
                ModelState.AddModelError(String.Empty, EX.Message);
            }



            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddOrRemoveUser(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null) return NotFound();

            ViewData["id"] = id;

            var usersinRole = new List<UsersInRoleViewModel>();
            var users = await _userManager.Users.ToListAsync();


            foreach (var item in users)
            {
                var userinRole = new UsersInRoleViewModel()
                {
                    UserId = item.Id,
                    UserName = item.UserName,
                };

                if (await _userManager.IsInRoleAsync(item, role.Name))
                {
                    userinRole.IsSelected = true;
                }
                else
                {
                    userinRole.IsSelected = false;
                }

                usersinRole.Add(userinRole);

            }


            return View(usersinRole);

        }

        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUser(string id, List<UsersInRoleViewModel> models)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null) return NotFound();


            if (ModelState.IsValid)
            {

                foreach (var item in models)
                {
                    var appuser = await _userManager.FindByIdAsync(item.UserId);
                    if (appuser is not null)
                    {
                        if (item.IsSelected && ! await _userManager.IsInRoleAsync(appuser,role.Name))
                        {
                            await _userManager.AddToRoleAsync(appuser, role.Name);
                        }
                        else if(!item.IsSelected && await _userManager.IsInRoleAsync(appuser, role.Name))
                        {
                            await _userManager.RemoveFromRoleAsync(appuser, role.Name);

                        }

                    }


                }


                return RedirectToAction("Edit", new { id = id });
            }

            return View(models);

        }


    }
}

app3_PL/Controllers/UserController.cs
using app3.BLL;
using app3.BLL.interfacees;
using app3.DaL.models;
using app3.PL.Helper;
using app3.PL.ViewModel;
using app3.PL.ViewModel.Employee;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace app3.PL.Controllers
{
    [Authorize(Roles ="Admin")]
    public class UserController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;

		public UserController(UserManager<ApplicationUser> userManager)
        {
			_userManager = userManager;
		}

		public async Task<IActionResult> Index(string inputSearch)
		
        {
			var users = Enumerable.Empty<UserViewModel>();

			if (string.IsNullOrEmpty(inputSearch))
			{
				 users= await _userManager.Users.Select(u => new UserViewModel()
				{
					Id = u.Id,
					FirstName = u.FirstName,
					LastName = u.LastName,
					Email = u.Email,
					Roles = _userManager.GetRolesAsync(u).Result
				}).ToListAsync();

			}
			else
			{
				users=await _userManager.Users.Where(u => u.Email
				                  .ToLower()
								  .Contains(inputSearch.ToLower()))
					              .Select(u=>new UserViewModel()
								  {
									  Id = u.Id,
									  FirstName = u.FirstName,
									  LastName = u.LastName,
									  Email = u.Email,
									  Roles = _userManager.GetRolesAsync(u).Result
								  }).ToListAsync();
			}



			return View(users);
		}


        public async Task<IActionResult> Details(string? id, string viewName = "Details")
        {
           
            if (id is null)
            {

                return BadRequest();//400
            }
			  var userfromDb=await _userManager.FindByIdAsync(id);

			if (userfromDb == null) return NotFound();
			var user = new UserViewModel()
			{
				Id = userfromDb.Id,
				FirstName = userfromDb.FirstName,
				LastName = userfromDb.LastName,
				Email = userfromDb.Email,
				Roles = _userManager.GetRolesAsync(userfromDb).Result
			};


            return View(viewName, user);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
         
            return await Details(id, "Edit");
        }


        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] string? id, UserViewModel model)
        {

            try
            {
                if (id != model.Id) return BadRequest();

              
                    var userfromDb = await _userManager.FindByIdAsync(id);

                    if (userfromDb == null) return NotFound();

                userfromDb.FirstName = model.FirstName;
                userfromDb.LastName = model.LastName;
                userfromDb.Email = model.Email;
                  
           
                var count = await _userManager.UpdateAsync(userfromDb);

                if (count.Succeeded)
                {
                    return RedirectToAction("Index");
                }

            }
            catch (Exception EX)
            {
                ModelState.AddModelError(String.Empty, EX.Message);
            }



            return View(model);

        }

        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {

            return await Details(id, "Delete");
        }



        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed([FromRoute] string id, UserViewModel model)
        {
            try
            {
                if (id != model.Id) return BadRequest();


                var userfromDb = await _userManager.FindByIdAsync(id);

                if (userfromDb == null) return NotFound();

                var count = await _userManager.DeleteAsync(userfromDb);

                if (count.Succeeded)
                {
                    return RedirectToAction("Index");
                }

            }
            catch (Exception EX)
            {
                ModelState.AddModelError(String.Empty, EX.Message);
            }

            return RedirectToAction("Delete");

        }



    }
}

app3_PL/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib SignUp Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/AuthStyleSheet.css" rel="stylesheet" type="text/css" media="all" />
	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative SignUp Form</h1>

		@RenderBody()


		
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
</body>
</html>

app3_PL/Views/Shared/_ButtonPartialView.cshtml
@model string

<td>
    <a asp-action="Details" asp-route-id="@Model" class="btn btn-warning">Details</a>
</td>
<td>
    <a asp-action="Edit" asp-route-id="@Model" class="btn btn-success">Update</a>
</td>
<td>
    <a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">Delete</a>
</td>

app3_PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - app3_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/app3_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Company</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark btn btn-warning" asp-area="" asp-controller="Account" asp-action="SignOut">Log Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("hamada", required: false)
</body>
</html>